name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    -
     name: Setup docker
     uses: docker/setup-buildx-action@v2
    -
     name: Login Docker hub
     uses: docker/login-action@v2
     with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
    -    
     name: test
     uses: docker/build-push-action@v3
     with:
       push: true
       tags: ${{secrets.DOCKERHUB_USERNAME}}/test:latest
       context: test        
    -    
     name: Build y push Docker image spring
     uses: docker/build-push-action@v3
     with:
       push: true
       tags: ${{secrets.DOCKERHUB_USERNAME}}/spring:latest
       context: venta
    -    
     name: Build y push Docker image angular
     uses: docker/build-push-action@v3
     with:
       push: true
       tags: ${{secrets.DOCKERHUB_USERNAME}}/angular:latest
       context: vista	   
